name = "EndSorry"
version = "0.1.0"
defaultTargets = ["EndSorry"]
testDriver = "EndSorryTest"
lintDriver = "runLinter"

[[lean_lib]]
name = "EndSorry"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4.git"

[[lean_lib]]
name = "EndSorryTest"
globs = ["EndSorryTest.+"]

[[lean_exe]]
name = "runLinter"
srcDir = ".lake/packages/batteries/scripts"
supportInterpreter = true